'use strict';
const paths={building:'M3 21h18M6 21V5l6-3 6 3v16M9 7h1m4 0h1M9 11h1m4 0h1M9 15h1m4 0h1M11 21v-3h2v3',nhc:'M3 21V10l5-4 5 4v11M13 21V6l4-3 4 3v15M6 13h3m-3 4h3m7-8h2m-2 4h2m-2 4h2',cars:'M4 16H3V9l2-5h14l2 5v7h-1M3 10h18M7 14h1m8 0h1M5 16h14M5 16v3h3v-3m8 0v3h3v-3',office:'M3 21h18M4 21V9h16v12M3 9l2-6h14l2 6M8 21v-7h8v7',marketing:'M4 5h16v12H4zM9 21h6m-3-4v4M8 13l3-3 2 2 4-5',phone:'M8 3H4l-1 2c0 8 8 16 16 16l2-1v-4l-5-2-2 2a14 14 0 0 1-6-6l2-2-2-5Z',save:'M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5',pin:'M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',search:'M21 21l-6-6M17 10A7 7 0 1 1 3 10a7 7 0 0 1 14 0',back:'M5 12h14m-5-5 5 5-5 5',external:'M14 3h7v7M21 3l-9 9M10 3H3v18h18v-7',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M13 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0M22 21v-3a4 4 0 0 0-4-4m-1-12a4 4 0 0 1 0 8',wa:'M21 11.5a9.5 9.5 0 0 1-14 8.4L3 21l1.2-4A9.5 9.5 0 1 1 21 11.5ZM8 7l2 3-1 1c1 2 2 3 4 4l1-1 3 1c-1 3-4 3-7 0s-4-6-2-8Z'};
const icon=k=>`<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[k]||paths.building}"/></svg>`;
paths.share='M12 16V3m-5 5 5-5 5 5M5 13v7h14v-7';
const cats=[{id:'nhc',name:'وجهات NHC',unit:'وجهات',icon:'nhc'},{id:'developers',name:'المطورون',unit:'جهة',icon:'building'},{id:'marketing',name:'شركات التسويق',unit:'جهات',icon:'marketing'},{id:'offices',name:'المكاتب والوسطاء العقاريون',unit:'مكاتب',icon:'office'},{id:'cars',name:'معارض السيارات',unit:'معرضًا',icon:'cars'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ar=n=>Number(n).toLocaleString('en-US');
const digits=n=>String(n).replace(/[^0-9]/g,'');
const intl=n=>{n=digits(n);return /^0[15]/.test(n)?'966'+n.slice(1):n};
const telephone=n=>'tel:'+(/^966/.test(intl(n))?'+'+intl(n):intl(n));
const contactFile=(r,c)=>'contacts/'+r.id+'-'+digits(c.phone)+'.vcf';
let records=[],query='',selected='nhc';
const category=id=>cats.find(c=>c.id===id)||cats[0];
function wa(c){return 'https://api.whatsapp.com/send?phone='+intl(c.phone)}
function shareButton(r,c){return `<button type="button" class="action share-action" data-share-id="${esc(r.id)}" data-share-phone="${esc(c.phone)}" title="مشاركة" aria-label="مشاركة جهة الاتصال ${esc(c.name)} لدى ${esc(r.name)}">${icon('share')}</button>`}
function priceMarkup(value){if(!value)return '';if(value==='غير معلن')return '<div class="price-display undisclosed"><span>السعر</span><strong>غير معلن</strong></div>';const m=/^تبدأ من ([\d,]+) ريال$/.exec(value);return m?`<div class="price-display"><span>تبدأ من</span><strong dir="ltr">${esc(m[1])}</strong><span>ريال</span></div>`:`<div class="price-display"><strong>${esc(value)}</strong></div>`}
function sales(r){return r.contacts||[]}
function projectContact(v){return records.find(r=>r.name===v.developer)?.contacts||[]}
function fullContact(c,r){const mobile=/^05\d{8}$/.test(digits(c.phone));return `<div class="contact"><div class="contact-person"><span class="contact-label">${['المكتب','المبيعات'].includes(c.name)?'التواصل':'مسؤول التواصل'}</span><strong class="contact-name">${esc(c.name)}</strong><a class="phone" href="tel:${esc(c.phone)}" dir="ltr">${esc(c.phone)}</a></div><div class="actions contact-actions"><a class="action primary" href="tel:${esc(c.phone)}" title="اتصال" aria-label="اتصال بـ ${esc(c.name)} لدى ${esc(r.name)}">${icon('phone')}</a>${mobile?`<a class="action wa" href="${wa(c)}" target="_blank" rel="noopener noreferrer" title="واتساب" aria-label="واتساب ${esc(c.name)} لدى ${esc(r.name)}">${icon('wa')}</a>`:''}<a class="action save-contact" href="${contactFile(r,c)}?download=1" download="contact-${r.id}-${digits(c.phone)}.vcf" type="text/vcard" title="حفظ جهة الاتصال" aria-label="حفظ جهة الاتصال ${esc(c.name)} لدى ${esc(r.name)}">${icon('save')}</a>${shareButton(r,c)}</div></div>`}
function mapAction(url){return url?`<a class="action map-action" href="${esc(url)}" target="_blank" rel="noopener" title="قوقل ماب" aria-label="فتح الموقع في خرائط قوقل"><img class="maps-symbol" src="google-maps.svg" alt=""></a>`:''}
function siteAction(url,label="صفحة المشروع"){return url?`<a class="action website-action" href="${esc(url)}" target="_blank" rel="noopener" aria-label="${esc(label)}">${esc(label)}</a>`:''}
function inlineProject(v,r){return `<section class="inline-project"><div class="inline-project-heading"><h4>${esc(v.name)}</h4>${v.stage?`<span class="stage">${esc(v.stage)}</span>`:''}</div><div class="project-summary">${v.location?`<span>${icon('pin')}${esc(v.location)}</span>`:''}${v.type?`<span class="project-type">${esc(v.type)}</span>`:''}</div>${priceMarkup(v.price)}<div class="actions">${mapAction(v.maps)}${siteAction(v.website,v.stage==='حجز الوحدات'?'حجز الوحدات':'صفحة المشروع')}</div></section>`}
function destination(r){return `<section class="destination-group" id="entity-${esc(r.id)}"><div class="destination-heading"><div><h3>${esc(r.name)}</h3>${r.units?`<span class="tag">${esc(r.units)} وحدة مخططة</span>`:''}</div><div class="actions">${mapAction(r.maps)}${siteAction(r.website,'صفحة الوجهة')}</div></div><div class="grid">${r.projects.map(v=>{const owner=records.find(x=>x.name===v.developer);return `<article class="record nhc-project"><div class="record-open"><span class="entity-label">المشروع</span>${inlineProject(v,r)}<div class="project-developer"><span>المطور</span><strong>${esc(v.developer)}</strong></div></div>${owner?.contacts?.length?`<div class="card-contacts">${owner.contacts.map(c=>fullContact(c,owner)).join('')}</div>`:''}</article>`}).join('')}</div></section>`}
function card(r){if(r.category==='nhc'&&r.projects.length)return destination(r);const c=category(r.category),cs=sales(r),ps=r.projects||[];const loc=r.location||[...new Set(ps.map(v=>v.location).filter(Boolean))].join(' · ');return `<article class="record" id="entity-${esc(r.id)}"><div class="record-open"><div class="record-icon"><span class="icon-box">${icon(c.icon)}</span><span class="tag">${r.category==='nhc'?'وجهة سكنية':esc(c.name)}</span></div><span class="entity-label">${r.category==='cars'?'المعرض':r.category==='offices'?'المكتب':r.category==='developers'?'المطور':'الجهة'}</span><h3>${esc(r.name)}</h3>${loc?`<p class="location">${icon('pin')}<span>${esc(loc)}</span></p>`:''}${r.units?`<div class="record-meta"><span>${esc(r.units)} وحدة مخططة</span></div>`:''}<div class="actions entity-actions">${mapAction(r.maps)}${siteAction(r.website,'الموقع الرسمي')}</div></div>${cs.length?`<div class="card-contacts">${cs.map(x=>fullContact(x,r)).join('')}</div>`:''}${ps.length?`<div class="card-projects"><div class="project-list-label">المشاريع</div>${ps.map(v=>inlineProject(v,r)).join('')}</div>`:''}</article>`}
function intro(){return '<section class="intro"><div><div class="eyebrow">دليل الفرص</div><h1>مركز مبيعات القادسية</h1></div></section>'}
function home(){selected=null;query='';document.title='مركز مبيعات القادسية | دليل الفرص';document.querySelector('#app').innerHTML=intro()+`<nav class="category-nav" aria-label="أقسام الدليل">${cats.map(c=>`<a href="#/${c.id}" class="category-choice category-${c.id}"><span class="category-symbol">${icon(c.icon)}</span><span class="category-name">${c.id==='offices'?'مكاتب العقار':esc(c.name)}</span><span class="category-total">${ar(records.filter(r=>r.category===c.id).length)}</span></a>`).join('')}</nav>`}
function destinationPicker(active){const places=records.filter(r=>r.category==='nhc');const current=places.find(r=>r.id===active);return `<details class="section-switcher"><summary aria-label="اختيار الوجهة">${icon('nhc')}<span>${current?esc(current.name):'اختر الوجهة'}</span><span class="switcher-chevron" aria-hidden="true">⌄</span></summary><nav aria-label="وجهات NHC">${places.map(r=>`<a href="#/nhc/${esc(r.id)}" class="switcher-link ${r.id===active?'active':''}" ${r.id===active?'aria-current="page"':''}>${esc(r.name)}</a>`).join('')}</nav></details>`}
function directory(id){selected=id;query='';const c=category(id);document.title=c.name+' | مركز مبيعات القادسية';const searchHint={nhc:'ابحث عن الوجهة أو المشروع أو المطور',developers:'ابحث عن المطور أو المشروع أو المسؤول',marketing:'ابحث عن الشركة أو المسؤول',offices:'ابحث عن المكتب أو المسؤول أو الحي',cars:'ابحث عن المعرض أو المسؤول'}[id];document.querySelector('#app').innerHTML=`<a class="back directory-back" href="#">${icon('back')}الرئيسية</a><div class="directory-head"><div class="directory-identity"><span class="directory-symbol">${icon(c.icon)}</span><div><div class="eyebrow">دليل الفرص</div><h1>${esc(c.name)}</h1></div></div><span class="directory-count">${ar(records.filter(r=>r.category===id).length)} ${esc(c.unit)}</span></div>${id==='nhc'?destinationPicker(null):''}<div class="worktop"><div><h2 id="listTitle" class="visually-hidden">${esc(c.name)}</h2><small id="resultCount"></small></div><div class="search">${icon('search')}<input type="search" id="search" aria-label="البحث في ${esc(c.name)}" placeholder="${esc(searchHint)}"></div></div><section id="results" class="grid" aria-labelledby="listTitle"></section>`;document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;listing()});listing()}

function norm(s){return String(s).normalize('NFKC').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/[\u064b-\u065f]/g,'').toLowerCase()}
function listing(){const q=norm(query.trim());const list=records.filter(r=>r.category===selected&&(!q||norm([r.name,r.location,r.district,...(r.contacts||[]).flatMap(c=>[c.name,c.phone]),...(r.projects||[]).flatMap(v=>[v.name,v.location,v.developer,v.type])].join(' ')).includes(q)));document.querySelector('#resultCount').textContent=ar(list.length)+' '+(list.length===1?'جهة':'جهات');document.querySelector('#results').innerHTML=list.length?(!q&&selected==='offices'?['القادسية','المونسية','الرمال','اليرموك','إشبيلية','الخليج','السعادة','شرق الرياض'].map(d=>{const group=list.filter(r=>r.district===d);return group.length?`<section class="district-group"><div class="district-title"><h3>${esc(d)}</h3><span>${ar(group.length)} جهات</span></div><div class="grid">${group.map(card).join('')}</div></section>`:''}).join(''):list.map(card).join('')):`<div class="empty" style="grid-column:1/-1"><strong>لا توجد نتائج</strong>جرّب اسمًا آخر في هذا القسم.<br><button class="action" id="clearSearch">مسح البحث</button></div>`;document.querySelector('#clearSearch')?.addEventListener('click',()=>{query='';document.querySelector('#search').value='';listing()})}

function detail(r){const c=category(r.category);document.title=r.name+' | مركز مبيعات القادسية';document.querySelector('#app').innerHTML=`<a class="back directory-back" href="#/${r.category}">${icon('back')}وجهات NHC</a>${r.category==='nhc'?destinationPicker(r.id):''}<div class="single-record">${card(r)}</div>`}
function route(){const pieces=location.hash.slice(1).split('/').filter(Boolean);const c=cats.find(x=>x.id===pieces[0]);if(!c)home();else if(pieces[1]){const r=records.find(x=>x.id===pieces[1]&&x.category===c.id);if(r)detail(r);else directory(c.id)}else directory(c.id);window.scrollTo(0,0)}
function shareText(r,c){const lines=[r.name,c.name+' · '+c.phone,r.location];if(r.maps)lines.push('الموقع: '+r.maps);if(r.website)lines.push('الموقع الرسمي: '+r.website);return lines.filter(Boolean).join('\n')}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
document.querySelector('#app').addEventListener('click',async e=>{const b=e.target.closest('[data-share-id]');if(!b)return;const r=records.find(x=>x.id===b.dataset.shareId),c=r?.contacts?.find(x=>x.phone===b.dataset.sharePhone);if(!r||!c)return;
  try{const text=shareText(r,c);if(navigator.share)await navigator.share({title:r.name,text});else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);toast('تم نسخ بيانات جهة الاتصال')}else toast('المشاركة غير متاحة في هذا المتصفح')}
  catch(error){if(error.name!=='AbortError')toast('تعذر فتح المشاركة، حاول مرة أخرى')}});

window.addEventListener('hashchange',route);
fetch('data.json').then(r=>{if(!r.ok)throw new Error('load');return r.json()}).then(data=>{records=data;route()}).catch(()=>document.querySelector('#app').innerHTML='<div class="empty"><strong>تعذر تحميل البيانات</strong>حدّث الصفحة لإعادة المحاولة.</div>');
