const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
class El { constructor(id){this.id=id;this.innerHTML='';this.textContent='';this.value='';this.dataset={};this.disabled=false;this.hidden=false;this.handlers={};this.classList={contains:()=>false};} addEventListener(k,f){this.handlers[k]=f;} querySelectorAll(){return [];} setAttribute(){} getAttribute(){return null;} focus(){} }
const els={};const document={title:'',body:{appendChild(){}},getElementById(id){if(id==='site-config')return null;return els[id]||(els[id]=new El(id));},querySelector(){return null;},querySelectorAll(){return [];},addEventListener(){},createElement(){return new El('new');}};
const location={hash:'',pathname:'/',search:''};const localStorage={getItem(){return null},setItem(){},removeItem(){}};const window={location,scrollTo(){},addEventListener(){}};
const fetch=async u=>{const p=path.join(root,u.split('?')[0]);return {ok:fs.existsSync(p),json:async()=>JSON.parse(fs.readFileSync(p,'utf8'))}};
let src=fs.readFileSync(path.join(root,'assets/app.js'),'utf8').replace('  boot();',`  window.__t={selectBranch,itemsFor,rawItems,nearbyItems,unlocatedItemsFor,nearestBranch,employeeGreeting,cities,sameCity,radiusApplies,setScope:(x,r)=>{S.scope=x;S.radius=r||15;return compute()},data:()=>D,state:()=>S}; boot();`);
vm.runInNewContext(src,{document,window,location,history:{replaceState(){}},localStorage,navigator:{},fetch,setTimeout,clearTimeout,console,URL,Blob});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await sleep(300);const A=window.__t,D=A.data(), kinds=['projects','opps','nhc','selfbuild','companies','offices','cars'];
 const result={branches:D.branches.length,displayCities:A.cities().length,scopeRows:0,scopePassed:0,failures:[],checks:[]};
 const parseCSV=s=>{const rows=[];let row=[],v='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c=='"'&&s[i+1]=='"'){v+='"';i++}else if(c=='"')q=false;else v+=c}else if(c=='"')q=true;else if(c==','){row.push(v);v=''}else if(c=='\n'){row.push(v);rows.push(row);row=[];v=''}else if(c!='\r')v+=c;}if(v||row.length){row.push(v);rows.push(row)}return rows};
 const csv=parseCSV(fs.readFileSync(path.join(__dirname,'scope_test_cases.csv'),'utf8').replace(/^\uFEFF/,'')), ix=Object.fromEntries(csv[0].map((v,i)=>[v,i]));
 for(const row of csv.slice(1).filter(r=>r.length>1)){const code=row[ix['الرمز']],kind=row[ix['القسم']];if(!kinds.includes(kind))continue;result.scopeRows++;const b=D.branchByCode[code];if(!b){result.failures.push({code,kind,error:'branch missing'});continue}A.selectBranch(code,true);const raw=A.rawItems(kind),vis=A.itemsFor(kind,''),city=A.itemsFor(kind,'','city'),un=A.unlocatedItemsFor(kind);const regionalCars=kind==='cars'&&A.sameCity(b.city,'الرياض');const applies=A.radiusApplies(kind,'branch')&&!regionalCars;const nearCount=applies?raw.filter(x=>(kind==='companies'?x.d:x.rankD)!=null&&(kind==='companies'?x.d:x.rankD)<=15).length:raw.length;const serviceExtras=kind==='companies'?vis.filter(x=>x.serviceMatch&&x.d!=null&&x.d>15).length:0;const unknownRaw=applies?raw.filter(x=>(kind==='companies'?x.d:x.rankD)==null).length:0;const expected=applies?nearCount+unknownRaw+serviceExtras:raw.length;const foreign=vis.filter(x=>!(kind==='companies'&&Array.isArray(x.o.coverageCities)&&x.o.coverageCities.length?x.o.coverageCities.some(c=>A.sameCity(c,b.city)):A.sameCity(x.o.city,b.city))).length;const invalid=applies?vis.filter(x=>(kind==='companies'?x.d:x.rankD)!=null&&(kind==='companies'?x.d:x.rankD)>15&&!(kind==='companies'&&x.serviceMatch)).length:0;
 if(vis.length===expected&&city.length===raw.length&&!foreign&&!invalid&&!un.length)result.scopePassed++;else result.failures.push({code,kind,visible:vis.length,expected,city:city.length,raw:raw.length,foreign,invalid,unknownPanel:un.length});}
 const nationwide={branches:0,rows:0,failures:[]};
 for(const b of D.branches){A.selectBranch(b.c,true);nationwide.branches++;for(const kind of kinds){const raw=A.rawItems(kind),visible=A.itemsFor(kind,''),wholeCity=A.itemsFor(kind,'','city');nationwide.rows++;const applies=A.radiusApplies(kind,'branch')&&!(kind==='cars'&&A.sameCity(b.city,'الرياض'));const outside=applies?visible.filter(x=>kind==='companies'?(x.d!=null&&x.d>15&&!x.serviceMatch):(x.rankD!=null&&x.rankD>15)):[];const mismatch=visible.length!== (applies ? raw.filter(x=>kind==='companies'?(x.d==null||x.d<=15):(x.rankD==null||x.rankD<=15)).length + (kind==='companies'?visible.filter(x=>x.serviceMatch&&x.d!=null&&x.d>15).length:0) : raw.length);if(wholeCity.length!==raw.length||outside.length||mismatch) nationwide.failures.push({code:b.c,kind,raw:raw.length,visible:visible.length,city:wholeCity.length,outside:outside.length,mismatch});}}
 result.checks.push({check:'جميع الفروع والأقسام ضمن النطاق والمدينة',ok:nationwide.branches===248&&!nationwide.failures.length,branches:nationwide.branches,branchKindRows:nationwide.rows,failures:nationwide.failures.slice(0,8)});
 const b242=D.branchByCode['242'];result.checks.push({check:'242 غرب الرياض',ok:b242.sec==='غرب'});
 const curatedPhones=['0507218678','0540998075','0539444885','0537031513','0536623945','0510686130','0500781804','0547777703','0561047060','0557004484','0554715999','0555299169','0554444604'];A.selectBranch('242',true);const westCars=A.itemsFor('cars','');const allWest=curatedPhones.every(p=>westCars.some(x=>(x.o.phones||[]).includes(p)));const westOk=westCars.length===13&&westCars.every(x=>x.o.zone==='shifa'&&x.o.lat==null&&x.o.lon==null&&!!x.o.maps)&&allWest;A.selectBranch('243',true);const eastCars=A.itemsFor('cars','');A.state().carArea='shifa';const otherCars=A.itemsFor('cars','');result.checks.push({check:'معارض الرياض بحسب القطاع وفلتر المنطقة الأخرى',ok:westOk&&eastCars.length===30&&eastCars.every(x=>x.o.zone==='qadisiyah')&&otherCars.length===13&&otherCars.every(x=>x.o.zone==='shifa'),west:westCars.length,east:eastCars.length,otherArea:otherCars.length});
 const b243=D.branchByCode['243'];A.selectBranch('243',true);const near=A.itemsFor('projects',''), city=A.itemsFor('projects','','city'), unknown=A.unlocatedItemsFor('projects');result.checks.push({check:'243 نطاق 15كم يُبقي السجلات بلا مسافة ويُوسع المدينة',ok:near.length<city.length&&near.every(x=>x.rankD==null||x.rankD<=15)&&city.length===((D.cityCount.projects||{}).الرياض||0)&&unknown.length===0,near:near.length,city:city.length,unknown:unknown.length});
 result.checks.push({check:'اختيارات 5/10/15 كم ظاهرة',ok:[5,10,15,20].every(x=>els.app.innerHTML.includes('أقرب '+x+' كم'))});
 result.checks.push({check:'لا تظهر لوحة أو أعداد للموقع غير المحدد',ok:!els.content.innerHTML.includes('موقع غير محدد')&&!els.content.innerHTML.includes('unlocated-panel')});
 result.checks.push({check:'أسماء الأحساء والهفوف والمبرز توحدت دون دمج المدن المستقلة',ok:A.sameCity('الأحساء','الهفوف')&&A.sameCity('الأحساء','المبرز')&&A.cities().length===77&&A.sameCity(D.branchByCode['273'].city,'بريدة')&&A.sameCity(D.branchByCode['405'].city,'الوجه')&&A.sameCity(D.branchByCode['271'].city,'الدرعية')&&A.sameCity(D.branchByCode['215'].city,'ليلى'),count:A.cities().length});
 A.selectBranch('271',true);const nearbyRadius=[5,10,15,20].map(r=>{A.setScope('branch',r);const xs=A.nearbyItems();return {radius:r,ok:xs.every(x=>x.d==null||x.d<=r),outside:xs.filter(x=>x.d!=null&&x.d>r).length}});result.checks.push({check:'فرص المدن المجاورة تحترم مسافة النطاق',ok:nearbyRadius.every(x=>x.ok),radii:nearbyRadius});
 const nearest=A.nearestBranch({lat:b243.lat,lon:b243.lon});result.checks.push({check:'أقرب فرع 243',ok:nearest&&nearest.c==='243'});
 const rakez=A.itemsFor('companies','').find(x=>x.o.n.includes('راكز'));result.checks.push({check:'راكز تحفظ القطاعات الخمسة',ok:!!rakez&&rakez.o.sectors.length===5});
 const companies=[['cp-ee28fb1fee','بريدة'],['cp-8ece8e6ede','الرياض'],['cp-c55e51e166','الدمام'],['cp-ebb24055cf','جدة'],['cp-df5fe89eac','صفوى'],['cp-fb2d83ba98','الدمام'],['cp-1b41c1ed02','مكة المكرمة'],['cp-c566adf828','جدة'],['cp-d0bacbed29','بريدة'],['cp-0912454315','مكة المكرمة'],['cp-4737529953','خميس مشيط']];
 const cv=companies.map(([id,city])=>{const b=D.branches.find(x=>A.sameCity(x.city,city));if(!b)return {id,city,ok:false};A.selectBranch(b.c,true);A.setScope('city');return {id,city,ok:A.itemsFor('companies','','city').filter(x=>x.o.id===id).length===1}});result.checks.push({check:'تغطية الشركات الجديدة تظهر مرة واحدة بالمدينة',ok:cv.every(x=>x.ok),coverage:cv});
 result.checks.push({check:'تحية الموظف بالوقت',ok:/^(صباح الخير|مساء الخير)، خالد$/.test(A.employeeGreeting('خالد'))});
 result.ok=result.scopeRows===result.scopePassed&&!result.failures.length&&result.checks.every(x=>x.ok);console.log(JSON.stringify(result,null,2));})();
